# Generated by Django 5.0.6 on 2024-06-22 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_fotos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fotos',
        ),
    ]
