# Generated by Django 5.0.6 on 2024-06-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_delete_fotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='foto_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
