# Generated by Django 5.0.6 on 2024-06-25 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0006_carrito'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
    ]
