# Generated by Django 5.0.6 on 2024-07-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0007_delete_alumno_delete_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='foto_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
